const regras = (prefix, sender) => {
	return BEM VINDO(A) AS REGRAS🔥

GTA SÃO PAULO (ROLEPLAY PS3) 

REGRAS DO GRUPO ⬇️

❗RESPEITAR MEMBROS E ADM
❗NÃO FALAR PALAVRÃO
❗NÃO DISCUTIR, E NEM PROVOCAR
❗NÃO MANDAR VÍDEOS PORNOGRÁFICOS
❗NÃO COMPARTILHAR LINK DE OUTROS GRUPOS

LINK DO DISCORD: https://discord.gg/gxyjkqfu

AO ENTRAR LEAM AS REGRAS, POIS PARA FAZER SEU REGISTRO SERÁ NECESSÁRIO CONHECIMENTO COM RP! 

DONOS 👨‍💼

@GUILHERME
@JUNIOR

ADM 👷🏼‍♂️

@MATHEUS
@MOISES
@ANDRE

NÃO PEDIR ADM, AO DECORRER DO TEMPO VAMOS PRESENTEAR MEMBROS FIEIS E QUE RESPEITAM AO GERAL!!`
}

exports.regras = regras
